/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;


/**
 *
 * @author campitos
 */
public class FrameSolucion extends javax.swing.JFrame {

    JRadioButton radios[];
    test.Opcion []opciones;

    Pregunta []preguntas=new Pregunta[2];
    int indice;
     
    public FrameSolucion() {
        initComponents();
         setLocationRelativeTo(this); 
        
        
        //Generamos en un arreglo los radios button visuales
         radios=new JRadioButton[5];
         opciones=new test.Opcion[5];
        radios[0]=radio1;
        radios[1]=radio2;
        radios[2]=radio3;
        radios[3]=radio4;
 
        
        //LLenamos el modelo con los valores correcto en la la intefaz de usuario
          Opcion op1=new Opcion("La quesadillas", false);
        
           Opcion op2=new Opcion("La grasa", false); 
         Opcion op3=new Opcion("El azucar", true);
          Opcion op4=new Opcion("La contaminacion", false);
     
       
        opciones[0]=op1;
        opciones[1]=op2;
        opciones[2]=op3;
        opciones[3]=op4;
   
       
 preguntas[0]=new test.Pregunta("Esta es la principal causa del cancer", opciones);
 
 
 
 Opcion []opciones2=new Opcion[4];
 
 //LLenamos el modelo con los valores correcto en la la intefaz de usuario
          Opcion op21=new test.Opcion("Jalisco", false);
        
       Opcion op22=new test.Opcion("Michoacan", false); 
       Opcion op23=new test.Opcion("Coahuila", true);
       Opcion op24=new test.Opcion("Tamaulipas", false);
     
 preguntas[1]=new Pregunta("Todos tienen costas excepto..", opciones2);
 
        etiquetaTitulo.setText(preguntas[indice].titulo); 
        for(int i=0;i<radios.length;i++){
            radios[i].setText(preguntas[indice].opciones[i].titulo); 
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        etiquetaTitulo = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        checarRespuesta = new javax.swing.JButton();
        sguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTitulo.setText("etiquetaTitulo");

        buttonGroup1.add(radio1);
        radio1.setText("jRadioButton1");

        buttonGroup1.add(radio2);
        radio2.setText("jRadioButton2");

        buttonGroup1.add(radio3);
        radio3.setText("jRadioButton3");

        buttonGroup1.add(radio4);
        radio4.setText("jRadioButton4");

        checarRespuesta.setText("checar respuesta");
        checarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checarRespuestaActionPerformed(evt);
            }
        });

        sguiente.setText("siguiente");
        sguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio1)
                            .addComponent(radio2)
                            .addComponent(radio3)
                            .addComponent(radio4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(checarRespuesta)
                        .addGap(50, 50, 50)
                        .addComponent(sguiente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio2)
                .addGap(18, 18, 18)
                .addComponent(radio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checarRespuesta)
                    .addComponent(sguiente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarRespuestaActionPerformed
        // TODO add your handling code here:
        
        
         //BUscamos el radioButton seleccionado
        int indiceSeleccionado=0;
        for(int i=0;i<radios.length;i++){
            if(radios[i].isSelected()){
                indiceSeleccionado=i;
                break;
            }
        }
        System.out.println("El indice seleccionado es:"+indiceSeleccionado);
       
        JOptionPane.showConfirmDialog(this,""+evaluar(preguntas[indice], indiceSeleccionado));
        
        indice++;
    }//GEN-LAST:event_checarRespuestaActionPerformed

    private void sguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sguienteActionPerformed
        // TODO add your handling code here:
        
        
        
        etiquetaTitulo.setText(preguntas[indice].titulo); 
        for(int i=0;i<radios.length;i++){
            radios[i].setText(preguntas[indice].opciones[i].titulo); 
        }
        
        
        
    }//GEN-LAST:event_sguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checarRespuesta;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JButton sguiente;
    // End of variables declaration//GEN-END:variables


   public boolean evaluar(Pregunta p, int indiceSeleccionado){
        boolean correcta=false;
        if(p.opciones[indiceSeleccionado].correcta){
            correcta=true;
        }
        return correcta;
    }
}
